workflows:
  android-workflow:
    name: OpenRouter Watch
    instance_type: linux_x2
    max_build_duration: 60
    environment:
      vars:
        # Add any app-specific environment variables here
        PACKAGE_NAME: "com.example.openrouterwatch"
      java: 11
    cache:
      cache_paths:
        - ~/.gradle/caches
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: master
          include: true
    scripts:
      - name: Install Gradle
        script: |
          echo "Installing Gradle..."
          wget https://services.gradle.org/distributions/gradle-7.0.2-bin.zip
          unzip -q gradle-7.0.2-bin.zip
          export GRADLE_HOME=$PWD/gradle-7.0.2
          export PATH=$GRADLE_HOME/bin:$PATH
          gradle --version
      
      - name: Set up Gradle wrapper files
        script: |
          echo "Setting up Gradle wrapper..."
          gradle wrapper
          chmod +x gradlew
          ls -la
      
      - name: Build debug APK
        script: |
          gradle assembleDebug || ./gradlew assembleDebug || gradle build || ./gradlew build
      
      - name: Find and display APK
        script: |
          echo "Searching for APK files..."
          find . -name "*.apk"
          
          # Most likely location
          if [ -d "app/build/outputs/apk/debug" ]; then
            echo "Standard output directory found:"
            ls -la app/build/outputs/apk/debug
          fi
          
          # Alternative locations
          if [ -d "build/outputs/apk" ]; then
            echo "Alternative output directory found:"
            ls -la build/outputs/apk
          fi
          
          if [ -d "app/build/outputs" ]; then
            echo "Checking all outputs:"
            find app/build/outputs -name "*.apk"
          fi
    artifacts:
      - app/build/outputs/apk/debug/*.apk
      - build/outputs/apk/**/*.apk
      - app/build/outputs/**/*.apk
      - "**/*.apk"
    publishing:
      email:
        recipients:
          - jd21hinman@gmail.com # Replace with your actual email
