name: Android Build

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    
    - name: Build with Gradle
      run: ./gradlew assembleDebug
    
    - name: Check APK exists
      run: |
        ls -la app/build/outputs/apk/debug/ || echo "Debug APK directory not found"
        find app -name "*.apk" || echo "No APKs found in app directory"
    
    - name: Upload APK - Fixed
      uses: actions/upload-artifact@v2
      with:
        name: app-debug-apk
        path: app/build/outputs/apk/debug/*.apk
        if-no-files-found: error  # This will make the workflow fail if no APKs are found
