name: Console Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    
    - name: Make gradlew executable
      run: chmod +x gradlew
    
    - name: Build and display APK
      run: |
        # Build the APK
        ./gradlew assembleDebug
        
        # Find the APK
        APK_PATH=$(find app/build/outputs -name "*.apk" | head -1)
        
        if [ -z "$APK_PATH" ]; then
          echo "No APK found!"
          exit 1
        fi
        
        echo "APK built successfully at: $APK_PATH"
        echo "Size: $(ls -lh $APK_PATH | awk '{print $5}')"
        
        # Create a temporary web server to allow download
        echo "Starting temporary HTTP server for APK download..."
        cd $(dirname $APK_PATH)
        python3 -m http.server 8000 &
        HTTP_PID=$!
        
        # Display APK info for 60 seconds
        echo "APK available at http://localhost:8000/$(basename $APK_PATH) for 60 seconds"
        for i in {60..1}; do
          echo "Server will shut down in $i seconds..."
          sleep 1
        done
        
        # Clean up
        kill $HTTP_PID
