name: Setup Gradle

on:
  workflow_dispatch:  # This allows manual triggering

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      
      - name: Setup Gradle Wrapper
        run: |
          gradle wrapper --gradle-version 7.0.2
      
      - name: Commit Gradle Wrapper
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add gradle/wrapper/gradle-wrapper.jar
          git add gradle/wrapper/gradle-wrapper.properties
          git add gradlew
          git add gradlew.bat
          git commit -m "Add Gradle Wrapper"
          git push
