name: Simple Build

on:
  workflow_dispatch:  # Manual trigger only

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    
    - name: Make gradlew executable
      run: chmod +x gradlew
    
    - name: Build with Gradle
      run: ./gradlew assembleDebug
    
    - name: Find and display APK location
      if: success()
      run: |
        echo "Searching for APK files..."
        APK_FILES=$(find app/build/outputs -name "*.apk")
        
        if [ -z "$APK_FILES" ]; then
          echo "No APK files found!"
        else
          echo "APK files found:"
          for apk in $APK_FILES; do
            echo " - $apk ($(ls -lh $apk | awk '{print $5}'))"
          done
          
          # Base64 encode a small APK for direct download
          if [ $(ls -la $(echo "$APK_FILES" | head -1) | awk '{print $5}') -lt 5000000 ]; then
            echo "APK is small enough for base64 encoding"
            BASE64_APK=$(base64 -w 0 $(echo "$APK_FILES" | head -1))
            echo "::set-output name=apk_base64::$BASE64_APK"
            echo "To download: Copy the base64 string from the logs and decode it using:"
            echo "echo BASE64_STRING | base64 -d > openrouter-watch.apk"
          else
            echo "APK is too large for base64 encoding in logs"
          fi
        fi
